comment/urls.py
from django.urls import path

from comment.views import comment_create

app_name = "comment"

urlpatterns = [
    path('create', comment_create, name="create"),
]

config/urls.py
from django import urls
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.urls.conf import include
from lib.views import IndexTemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 管理者ページ
    path('admin/', admin.site.urls),
    path('recipe/', include("recipe.urls")),
    path('comment/', include("comment.urls", namespace="comment")),
    path('staffroom/', include("staffroom.urls", namespace="staffroom")),
    path('login', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout',
         LogoutView.as_view(template_name="index.html"),
         name="logout"),
    path('', IndexTemplateView.as_view(), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.contrib import admin
from django.urls import path
from lib.views import IndexTemplateView
from recipe.views import (RecipeListView, RecipeDetailView,
                          )

app_name = "recipe"

urlpatterns = [
    
    # レシピ一覧画面
    path('', RecipeListView.as_view(), name="index"),
    # レシピ詳細画面
    path('<int:pk>', RecipeDetailView.as_view(), name="detail"),
    

]

recipe/models.py
from enum import auto
from django.db import models
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill



# Create your models here.
class Recipe(models.Model):
    # タイトル
    title = models.CharField(max_length=200)
    # 内容
    content = models.TextField()
    # 特徴
    description = models.TextField(blank=True, default="")
    image = models.ImageField(upload_to="images/uploaded/", default=None, null=True, blank=True)
    detail_main = ImageSpecField(
        source="image",
        processors=[ResizeToFill(640, 480)],
        format="jpeg",
        options={"quality": 80}
    )
    # user
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             default=None,
                             null=True)
    # 作成日
    created = models.DateTimeField(auto_now_add=True)
    # 最終更新日
    modified = models.DateTimeField(auto_now=True)




# データベースにデータ反映する＝マイグレーション

staffroom/models.py
from django.db import models

# Create your models here.

comment/forms.py
from django import forms

from comment.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
            "recipe",
        ]
        widgets = {"recipe": forms.HiddenInput()}
        labels = {"content": "コメントをどうぞ"}

recipe/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "title",
            "content",
            "description",
            "image",
            "user",
        ]
        widgets = {"user": forms.HiddenInput()}

comment/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from comment.forms import CommentForm

# Create your views here.


# コメントを取得して保存
def comment_create(request):
    recipe_id = request.POST.get("recipe")
    content = request.POST.get("content")

    data = {"content": content, "recipe": recipe_id}

    form = CommentForm(data=data)

    if form.is_valid():
        form.save()
        messages.success(request, "コメントを投稿しました。")
    else:
        messages.error(request, "コメントが投稿できませんでした")

    return redirect("recipe:detail", pk=recipe_id)

lib/views.py
from django.views.generic import TemplateView

from recipe.models import Recipe

class IndexTemplateView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['recipe_top'] = Recipe.objects.order_by('?')[0]
        context['recipe_list'] = Recipe.objects.order_by("-created")
        
        return context

    def get_queryset(self):
        qs = Recipe.objects.all()
        keyword = self.request.GET.get("q")

        if keyword:
           qs = qs.filter(title__contains=keyword)
        return qs

recipe/views.py
# 汎用ビューの読み込み
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
# モデルの読み込み
from .models import Recipe
from comment.forms import CommentForm

from django.urls import reverse, reverse_lazy
from django import forms


# 自作クラスを定義、ビューを継承
# 一覧表示用のview
class RecipeListView(ListView):
    # 自作クラスにモデルを設定
    model = Recipe

    def get_queryset(self):
        qs = Recipe.objects.all()
        keyword = self.request.GET.get("q")

        if keyword:
            qs = qs.filter(title__contains=keyword)
        return qs


# レシピ作成用のview
class RecipeCreateView(CreateView):
    model = Recipe
    # form_class = forms
    fields = ["title", "content", "description", "image", "user"]
    success_url = reverse_lazy("recipe:index")


# 詳細表示用のview
class RecipeDetailView(DetailView):
    # recipe = Recipe.objects.get(id=pk)
    model = Recipe
    """ def get_context_date(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['CommentForm'] = CommentForm()

        return context """
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # self.object = self.get_object()
        # self.object = Recipe.objects.get(id=pk)
        context['CommentForm'] = CommentForm(initial={'recipe': self.object})

        return context


# レシピ更新用のview
class RecipeUpdateView(UpdateView):
    model = Recipe
    fields = ["title", "content", "description", "image"]

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        return reverse("recipe:detail", kwargs={"pk": pk})


# レシピ削除用のview
class RecipeDeleteView(DeleteView):
    model = Recipe
    success_url = reverse_lazy("recipe:index")

staffroom/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, CreateView, DeleteView, UpdateView
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from recipe.models import Recipe
from recipe.forms import RecipeForm


class StaffroomMixin(LoginRequiredMixin):
    login_url = reverse_lazy("login")


class StaffroomTemplateView(StaffroomMixin, TemplateView):
    template_name = "staffroom/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            context['recipe_list'] = Recipe.objects.filter(
                user=self.request.user)
        else:
            context['recipe_list'] = None

        return context


class RecipeCreateView(StaffroomMixin, CreateView):
    login_url = reverse_lazy("login")
    model = Recipe
    form_class = RecipeForm
    success_url = reverse_lazy("recipe:index")

    def post(self, request, *args, **kwargs):
        user = request.user
        data = request.POST.dict()
        data['user'] = user.id
        form = RecipeForm(data=data, files=request.FILES)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        messages.success(self.request, "保存しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "保存できませんでした")
        return super().form_invalid(form)


class RecipeUpdateView(StaffroomMixin, UpdateView):
    login_url = reverse_lazy("login")
    model = Recipe
    fields = ["title", "content", "description", "image"]

    def get_success_url(self):
        pk = self.kwargs.get("pk")
        return reverse("recipe:detail", kwargs={"pk": pk})

    def form_valid(self, form):
        messages.success(self.request, "更新しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "更新できませんでした")
        return super().form_invalid(form)


class RecipeDeleteView(StaffroomMixin, DeleteView):
    login_url = reverse_lazy("login")
    model = Recipe
    success_url = reverse_lazy("recipe:index")

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "削除しました")
        return super().delete(request, *args, **kwargs)

lib/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>レシピ投稿サイト　レシピポスト - Recipe Post</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{%  static 'css/small-business.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <link rel="stylesheet" href="css/small-business.css">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">{{ request.user.username }}レシピポスト</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> 
      
          
          <nav class="navbar navbar-dark bg-dark">
          <!-- Navbar content -->
          </nav>

          <ul class="nav">
          　
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'recipe:index' %}">レシピ</a>
            </li>
            {% if request.user.is_authenticated %}
            <li>
              <a class="nav-link text-white" href="{% url 'staffroom:recipe:create' %}">レシピ新規作成</a>
            </li>
            {% endif %}
            <li>
              <a class="nav-link text-white" href="{% url 'login' %}">ログイン</a>
            </li>
            <li>
              <a class="nav-link text-white" href="{% url 'logout' %}">ログアウト</a>
            </li>
            
          </ul>
        <!-- </ul> -->
      <!-- </div> -->
      <form class="form-inline">
        <input class="form-control mr-sm-2" name="q" value="{{ request.GET.q }}" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    {% block body %} {% endblock %}
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
  

 

  <!-- Footer -->
  <footer class="py-5 bg-dark mt-3">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

lib/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block body %}



<div class="row"><pre></div>

<div class="row">
  
  
  {% for recipe in recipe_list %}
      <div class="col-md-4 mb-5">
          <div class="card h-100">
              {% if recipe.image %}
                  <img class="card-img-top" src="{{ recipe.image.url }}" alt="{{ recipe.title }}"/>
              {% else %}
                  <img class="card-img-top" src="{% static 'images/01.jpg' %}" alt="{{ recipe.title }}"/>
              {% endif %}
              <div class="card-body">
                  <h2 class="card-title">{{ recipe.title }}</h2>
                  <p class="card-text">{{ recipe.description }}</p>
              </div>
              <div class="card-footer">
                  <a href="{% url 'recipe:detail' recipe.id %}" class="btn btn-primary btn-sm">詳細</a>
              </div>
          </div>
      </div>
  {% endfor %}



</div>


  {% endblock %}

lib/templates/login.html
{% load static %}
{% load crispy_forms_tags %}


<!DOCTYPE html>
<html lang="en">
    <head>
       

        
        <title>ログイン - Recipe Post</title>

        
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">

                                    
                                    <div class="card-header">
                                        <h3 class="text-center font-weight-light my-4">ログイン</h3>
                                    </div>
                                    <div class="card-body">
                                        <form method="post">
                                            {% csrf_token %}
                                            {{ form|crispy }}

                                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <button class="btn btn-primary">ログイン</button>
                                            </div>
                                        </form>
                                    </div>
                                    

                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

        
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

lib/templates/logout.html
{% extends "base.html" %}

{% block body %}

    <h1>ログアウトしました</h1>

{% endblock %}

recipe/templates/recipe/recipe_detail.html
{% extends "base.html" %} 
{% load static %} 
{% load crispy_forms_tags %} 
{% block body %}
<div class="row my-3">
  <div class="col-lg-12">
    <h1>{{ recipe.title }}</h1>
  </div>
  <div class="col-lg-7">
    {% if recipe.image %}
    <img
      src="{{ recipe.detail_main.url }}"
      width="640"
      class="img-fluid rounded border"
    />
    {% else %}
    <img
      src="{% static 'images/01.jpg' %}"
      width="640"
      class="img-fluid rounded border"
    />
    {% endif %}
  </div>
  <div class="col-lg-5">
    <h3>作り方</h3>
    <p>{{ recipe.content }}</p>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <h3>このレシピの説明</h3>
    <p>{{ recipe.description }}</p>
  </div>
</div>
<hr />

<div class="row">
  <div class="col">
    <p class="text-muted">投稿日:{{ recipe.created }}</p>
  </div>
  <div class="col">
    <p class="text-muted">変更日:{{ recipe.modified }}</p>
  </div>
</div>

<div class="row">
  <div class="col">
    <h3>コメント</h3>
    <ul class="list-unstyled">
      {% for comment in recipe.comment_set.all %}
      <li class="border-bottom mt-2">
        {{ comment.content }} -- ({{ comment.created }}
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

<div class="row">
  <div class="col">
    <form method="post" action="{% url 'comment:create' %}">
      {% csrf_token %} {{ CommentForm|crispy }}

      <button type="submit" class="btn btn-primary">送信</button>
    </form>
  </div>
</div>

{% if request.user.is_authenticated and request.user == recipe.user %}
<hr>
<div class="row">
  <div class="col">
    <a class="btn btn-info" href="{% url 'staffroom:recipe:update' recipe.id %}">編集</a>
    <a class="btn btn-danger" href="{% url 'staffroom:recipe:delete' recipe.id %}"
      >削除</a>
  </div>
</div>
{% endif %}

{% endblock %}

recipe/templates/recipe/recipe_list.html
{% extends "base.html" %}
{% load static %}

{% block body %}
      <h1>レシピ一覧</h1>

      {% for recipe in recipe_list %}

      <div class="media">
        {% if recipe.image %}
          <img src="{{ recipe.image.url }}" 
             class="align-self-center mr-3" alt="..." width="120">
        {% else %}
          <img src="{% static 'images/01.jpg' %}" 
             class="align-self-center mr-3" alt="..." width="120">
        {% endif %}
        <div class="media-body">
          <a href="{% url 'recipe:detail' recipe.id %}">
            <h5 class="mt-0">{{ recipe.title }}</h5>
          </a>
          <p>{{ recipe.description }}</p>
        </div>
      </div>
      {% if not forloop.last %}
      <hr>
      {% endif %}

      {% endfor %}
      
{% endblock %}

staffroom/templates/recipe/recipe_confirm_delete.html
{% extends "base.html" %}


{% block body %}
      <div class="my-5">
        <div class="row">
          <div class="col">
            <form method="post">
              {% csrf_token %}
              <p class="">
                本当に削除してもよろしいでしょうか？
              </p>

              <button type="submit" class="btn btn-danger">削除</button>
              <a href="{% url 'recipe:detail' recipe.id %}" class="btn btn-secondary">キャンセル</a>
            </form>
          </div>
        </div>
      </div>
      
{% endblock %}

staffroom/templates/recipe/recipe_form.html
{% extends "base.html" %}
{% comment %} {% extends "staffroom.html" %} {% endcomment %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item">Dashboard</li>
        <li class="breadcrumb-item">レシピ</li>
        <li class="breadcrumb-item active">新規作成</li>
    </ol>
{% endblock %}

{% block body %}

    <div class="row my-3">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}

                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-primary">保存</button>
                                {% if not "create" in request.path %}
                                    <a href="{% url 'recipe:detail' recipe.id %}" class="btn btn-secondary">キャンセル</a>
                                {% endif %}
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

staffroom/templates/staffroom.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        
        <!-- ▼▼▼ 編集 ▼▼▼ -->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
    <!-- 省略 -->

        <div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4"><a class="nav-link" href="{% url 'staffroom:index' %}">{{ request.user.username }}Dashboard</a></h1>  
            
            {% comment %} {% block breadcrumbs %} 
             <ol class="breadcrumb mb-4"> 
                 <li class="breadcrumb-item active">Dashboard</li> 
                 <a class="nav-link" href="{% url 'staffroom:index' %}">Dashboard</a> 
            </ol> 
            
            {% endblock %}  {% endcomment %}

            {% block body %}{% endblock %}
        </div>
    </main>
    
    <!-- 省略 -->
    </div>

        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        
        <!-- ▼▼▼ 編集 ▼▼▼ -->
        <script src="{% static 'js/scripts.js' %}"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        
        <!-- ▼▼▼ 編集 ▼▼▼ -->
        <script src="{% static 'assets/demo/datatables-demo.js' %}"></script>

    </body>
</html>

staffroom/templates/staffroom/index.html
{% extends 'staffroom.html' %}

{% block body %}

    <div class="col-lg-12">
        <div class="card">
        
            <div class="card-header">
                レシピ一覧
                
            </div>
            <div class="card-body">
              <table class="table">
                    {% for recipe in recipe_list %}
                        <tr>
                          <th>タイトル</th>
                          <th>レシピ作成日</th>
                        </tr>
                        <tr>
                            <td>{{ recipe.title }}</td>
                            <td>{{ recipe.created }}</td>
                        <tr/>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

     <div class="card mt-3">
            <div class="card-header">
                コメント一覧
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th>レシピ</th>
                        <th>コメント内容</th>
                        <th>コメント投稿日</th>
                    </tr>
                    </thead>
                    {% for recipe in recipe_list %}
                        {% for comment in recipe.comment_set.all %}
                            <tr>
                                <td>{{ recipe.title }}</td>
                                <td>{{ comment.content }}</td>
                                <td>{{ comment.created }}</td>
                            </tr>
                        {% endfor %}
                    {% endfor %}
                </table>
            </div>
        </div>

        <a href="{% url 'recipe:index' %}">レシピポストへ</a>

{% endblock %}